In [24]:
from keras.models import Sequential
from keras.layers.core import Dropout,Dense,activations,Flatten
from keras.layers.convolutional import MaxPooling2D,Convolution2D
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import keras

In [25]:
df=pd.read_csv('/home/talha/Documents/mnist.csv')

In [26]:
df.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 220, 179,   6,   0,   0,   0,   0,
          0,   0,   0,   0,   9,  77,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [28]:
df_x=df.iloc[:,1:].values.reshape(len(df),28,28,1)
df_y=df.iloc[:,0].values
df_y

array([1, 0, 1, ..., 7, 6, 9])

In [29]:
df_y=keras.utils.to_categorical(df_y,num_classes=10)
df_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [30]:
df_x=np.array(df_x)
df_y=np.array(df_y)
df_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [31]:
df_x.shape

(42000, 28, 28, 1)

In [32]:
df_y.shape

(42000, 10)

In [33]:
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [71]:
model=Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
#model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [72]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_19 (Conv2D)           (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_18 (MaxPooling (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_15 (Flatten)         (None, 5408)              0         
_________________________________________________________________
dense_29 (Dense)             (None, 100)               540900    
_________________________________________________________________
dropout_15 (Dropout)         (None, 100)               0         
_________________________________________________________________
dense_30 (Dense)             (None, 10)                1010      
Total params: 542,230
Trainable params: 542,230
Non-trainable params: 0
_________________________________________________________________


In [73]:
model.fit(x_train,y_train,validation_data=(x_test,y_test))

Train on 33600 samples, validate on 8400 samples
Epoch 1/1
33600/33600 [==============================] - 24s 704us/step - loss: 8.7786 - acc: 0.1316 - val_loss: 9.8268 - val_acc: 0.1921


In [75]:
model.predict(x_test[1:20])

array([[  722.8615  ,   131.83896 ,  -737.2135  ,   700.5068  ,
        -1209.358   ,   614.9505  ,  -351.50833 ,   807.2254  ,
         -953.20166 ,   254.99765 ],
       [ 1344.566   ,  -133.51228 , -1279.2179  ,   621.69885 ,
        -1660.9066  ,   652.4057  ,   255.20448 ,   787.9203  ,
        -1678.7198  ,  1036.3739  ],
       [  739.91003 ,  -247.71191 , -1001.82556 ,   820.08997 ,
         -833.6215  ,   514.6705  ,   -12.529345,   798.6716  ,
        -1177.1193  ,   435.53232 ],
       [  650.4153  ,   -94.48248 ,  -617.32336 ,    21.335869,
        -1142.7274  ,   570.65875 ,   461.60928 ,   493.00244 ,
         -828.9858  ,   335.44016 ],
       [  813.5867  ,   316.33792 , -1099.5422  ,   898.0249  ,
         -994.4963  ,   459.98456 ,  -363.32916 ,  1057.3927  ,
        -1224.0004  ,   185.4861  ],
       [  735.0606  ,  -167.35085 ,  -781.31476 ,   670.0659  ,
        -1220.1643  ,   724.6684  ,  -263.84512 ,   886.19745 ,
        -1028.2056  ,   341.377   ],
       [ 1

In [77]:
model.evaluate(x_test,y_test)

8400/8400 [==============================] - 2s 189us/step


[9.82682427360898, 0.19214285714285714]