In [13]:
import numpy as np
flag=False
row=0
column=0
row_str=""
col_str=""
f=open("/home/rana/mypython/file.txt")
for W in f:
    if flag==False:
        row=len(W)
        row_str=W
        #print(row_str,"=",row)
    else:
        column=len(W)
        col_str=W
        #print(col_str,"=",column)
    flag=True
f.close()
matrix=np.zeros((row,column),np.int32)
 
#scoring
sub_cost=input("enter substitution cost")
insrt_cost=input("enter insertion cost")
del_cost=input("enter deletion cost")
 
 
def _compute_array():
    for i in range(1, row):
        for j in range(1, column):
            matrix[i][j] = min(  matrix[i-1][ j-1] + _get_score(i, j),
                                    matrix[i-1][j] + int(del_cost),
                                    matrix[i][j-1] + int(insrt_cost))
def _get_score( i, j):
    if row_str[i-1]==col_str[j-1]:
        return 0
    else:
        return int(sub_cost) 
 
flag=True
matrix[0,0]=0
matrix[0,1]=1 
matrix[1,0]=1
for i in range(0,1):
    for j in range(2,column):
        matrix[i][j]=matrix[i][j-1]+1
for i in range(0,1):
    for j in range(2,row):
        matrix[j][i]=matrix[j-1][i]+1
_compute_array()
#_traceback()
print (matrix)

enter substitution cost 2
enter insertion cost 1
enter deletion cost 1


[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  6  7  8]
 [ 2  3  4  5  6  7  8  7  8  7]
 [ 3  4  5  6  7  8  7  8  9  8]
 [ 4  3  4  5  6  7  8  9 10  9]
 [ 5  4  5  6  7  8  9 10 11 10]
 [ 6  5  6  7  8  9  8  9 10 11]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 9  8  9 10 11 12 11 10  9  8]]


## jljljljlljlk